pub const SDE: [&'static str; 18] = [
    "When did you take a risk, make a mistake or fail? How did you respond?",
    "Tell me about a time you failed. How did you deal with the situation?",
    "Tell me about a time you had a conflict at work.",
    "Tell me about a time when you took the lead on a difficult project.",
    "Tell me about a time when you received negative feedback from your manager. How did you respond?",
    "How would you handle a project that is expected to be behind schedule?",
    "Describe a time when you received criticism and how you handled it.",
    "Tell me about a time you recovered from a difficult situation.",
    "Describe the most challenging project you've worked on so far.",
    "What is the most difficult decision you ever took in software?",
    "Tell me about a time you had to make a decision under pressure to meet a deadline.",
    "Tell me about a time when you had to choose between technologies for a project.",
    "Tell me about a time when you had to make a judgement call without having time to refer to a manager/supervisor.",
    "Give me an example where you strongly held an opinion and you were the outlier.",
    "What is the most significant impact of your work inside a team?",
    "What is the best invention or idea you had in the past two years?",
    "Tell me about a time you exceeded your expectations.",
    "Describe a project that you are particularly proud of. How did it impact your company? What challenges did you encounter and how did you solve them?",
];

pub const PM: [&'static str; 33] = [
    "Describe a time when you went outside normal procedures to get a project done.",
    "You are going to miss tomorrow's deadline, how do you and your team handle it?",
    "Give me a detailed example of the project you have led before to help me understand more of your previous job.",
    "What practical steps have you taken to elicit maximum contributions from each member of your team?",
    "What is the most innovative thing that you have created?",
    "In a situation where your intuition tells you there is a potential business opportunity, how do you go about finding the data necessary to substantiate it? Where do you even start?",
    "Tell us about your strengths.",
    "Describe a time that you exhibited leadership in your organization.",
    "Tell me about a time when a decision you made didn't produce the results you wanted.",
    "Tell me about a time when you disappointed a team member",
    "Tell me about a time when you had to deal with a difficult customer",
    "Give 3 examples of projects where you invented, simplified, delivered results quickly, and were able to scale to a larger result",
    "Tell me about a time when you proceeded to deal with an issue without your bosses OK.",
    "Please tell me about a time when you had a project in trouble and how you handled it.",
    "Tell me about a decision that did not go your way. How did you deal with it.",
    "What was a challenge you faced during a project you worked on and how did you overcome it.",
    "Describe a time you failed at work, or describe the most difficult situation you faced at work",
    "When in your last job did you take a risk and fail?",
    "How do you express different opinions to your manager?",
    "Give me an example of when you have failed at a task, what did you do?",
    "Tell me about a time when you innovated to simplify a process.",
    "Talk about a project that you took with ambiguity and lack of data, and how did you proceed with the project?",
    "Talk about a situation where you remotely influenced stakeholders and were able to get your work done. Explain the approach taken.",
    "Talk about a project where you had to take a difficult decision. Explain the decision, impact, reason for such decision, how did you handle it, and the result.",
    "Name a time you disagreed with your boss. How did the issue get solved?",
    "How did you train one of your team members, junior or senior to make him/her better in his/her daily work?",
    "A time when you took a calculated risk, pushed through with it and succeeded.",
    "A time when you used customer feedback to improve an aspect of your organization.",
    "A time when, halfway through a project, you encountered an incident/setback/roadblock and act to overcome it. With what result?",
    "Give me 5 examples of how you are working to better yourself.",
    "Tell me about the most innovative thing you have ever created.",
    "Name a time when you had to deal with a tough situation. Or, when you disagreed with management and what did you do.",
    "Tell me your most successful project which you led, what did you achieve at the end?",
];


pub const COMMON: [&'static str; 35] = [
    "Tell me about a time when you were not able to meet a time commitment. What was the outcome and what did you learn from it?",
    "Describe a long-term project that you managed. How did you keep everything moving along in a timely manner?",
    "Give me an example of a time when you set a goal and were able to meet or achieve it.",
    "Tell me about a time you had to quickly adjust your work priorities to meet changing demands.",
    "Give me an example when you had to push back to HQ or challenged a decision.",
    "Tell me about the toughest decision you've had to make in the past six months.",
    "Tell me about a decision that you regret.",
    "What did you do when you needed to motivate a group of individuals?",
    "Tell me about a time you stepped up into a leadership role.",
    "Do you collaborate well?",
    "Describe a situation when you negotiated with others in your organization to reach agreement.",
    "We've all had to work with people that don't like us. How do you deal with someone that doesn't like you?",
    "We all make mistakes we wish we could take back. Tell me about a time you wish you’d handled a situation differently with a colleague.",
    "Tell me about the last time you had to apologize to someone.",
    "Give me an example of a time you faced a conflict while working on a team. How did you handle that?",
    "Tell me about a time when you received negative feedback from your manager. How did you respond?",
    "Tell me about a time when you missed an obvious solution to a problem.",
    "A time when you faced a problem that had multiple possible solutions",
    "Tell me about a time when you came up with a new approach to a problem.",
    "Describe a time when you anticipated potential problems and developed preventive measures.",
    "Describe a situation in which you found a creative way to overcome an obstacle.",
    "How have you leveraged data to develop a strategy?",
    "Tell me about a time when you were 75% through a project, & you had to pivot strategy.",
    "Tell me about a time when you had to choose between technologies for a project.",
    "Tell me about a time you had to deal with ambiguity.",
    "What’s the most innovative new idea that you have implemented?",
    "Describe a time when you sacrificed short term goals for long term success.",
    "Provide an example of when you personally demonstrate ownership.",
    "What's your greatest strength?",
    "What's your biggest weakness?",
    "We all deal with difficult customers from time to time. Tell me about a challenging client-facing situation and how you handled it.",
    "How do you show customer obsession?",
    "Tell me about a time you recovered from a difficult situation.",
    "Tell me about a time you failed and what you learned from it.",
    "Why Amazon?",
];

pub const ALL: [&'static str; 157] = [
    "Tell me about a time when you faced a problem that had multiple possible solutions.",
    "When did you take a risk? Did you make a mistake or did you fail? How did you respond?",
    "What did you do when you needed to motivate a group of individuals?",
    "How have you leveraged data to develop a strategy?",
    "Tell me about a time when a team member didn't meet your expectations on a project.",
    "Tell me about a time when you failed and what you learned from it.",
    "Tell me about the last time you had to apologize to someone.",
    "Tell me about a time when you were 75% through a project and you had to pivot strategy?",
    "How do you show your customer obsession?",
    "How do you wow your customers?",
    "How do you develop client relationships?",
    "How do you understand your customer's needs?",
    "Describe a time when you made a judgement call with limited information.",
    "Describe a time when you improved a process with limited budget.",
    "Describe a problem you solved. What was the root cause of the problem?",
    "Give me an example when you had to push back to HQ or challenged a decision?",
    "Provide an example of when you personally demonstrate ownership.",
    "Tell me about a time when you went above and beyond.",
    "Tell me when you took on something outside your area of responsibility. What was the outcome?",
    "Give me an example when you saw a peer struggling and decided to step in and help.",
    "Describe a situation where you disagreed with a supervisor.",
    "Tell me about a time when you recovered from a difficult situation.",
    "Tell me about a time when you had to solve a difficult problem.", 
    "Describe a project or idea, not necessarily your own, that was implemented primarily because of your efforts.",
    "Do you feel you work well under pressure? If so, describe a time when you have done so.",
    "Give me an example of a time when you motivated others.",
    "Tell me about a time where you had to delegate tasks during a project.",
    "Give me an example of when you showed initiative and took the lead.",
    "Tell me about a time when you missed an obvious solution to a problem.",
    "Tell me about your proudest professional accomplishment.",
    "Tell me about a time when you handled a crisis.",
    "Tell me about a time you had to deal with ambiguity.",
    "Are you easy to get along with?",
    "Do you collaborate well?",
    "Tell me about a team project you worked on.",
    "Describe a time when you had to bring two departments together to work more efficiently with each other.",
    "Tell me about a time you stepped up into a leadership role.",
    "Tell me about a time you led an important meeting.",
    "How do you motivate other people to work with you?",
    "Describe your style in dealing with irate customers?",
    "Describe a difficult decision you've had to make in your business life and how you went about doing it?",
    "Tell me about a time you made a mistake that affected a client adversely and how you coped with it?",
    "Tell me about a time when you disagreed with a rule or approach?",
    "Describe a situation when you were able to use persuasion to successfully convince someone to see things your way?",
    "Tell me about a time when you were asked to take sides regarding another employee and you remained neutral?",
    "We've all had to work with people that don't like us. How do you deal with someone that doesn't like you?",
    "Give me an example of a time when you set a goal and were able to meet or achieve it.",
    "Describe a time when you went beyond your job description to save your company time and money.",
    "Give an example of a situation in which you took specific steps to further your career.",
    "Talk about a time when you had to work closely with someone whose personality was very different from yours.",
    "Give me an example of a time you faced a conflict while working on a team. How did you handle that?",
    "Describe a time when you struggled to build a relationship with someone important. How did you eventually overcome that?",
    "We all make mistakes we wish we could take back. Tell me about a time you wish you'd handled a situation differently with a colleague?",
    "Tell me about a time you needed to get information from someone who wasn't very responsive. What did you do?",
    "Describe a time when it was especially important to make a good impression on a client. How did you go about doing so?",
    "Give me an example of a time when you did not meet a client's expectation. What happened, and how did you attempt to rectify the situation?",
    "Tell me about a time when you made sure a customer was pleased with your service",
    "When you're working with a large number of customers, it's tricky to deliver excellent service to them all. How do you go about prioritizing your customers' needs?",
    "Tell me about a time you were under a lot of pressure. What was going on, and how did you get through it?",
    "Describe a time when your team or company was undergoing some change. How did that impact you, and how did you adapt?",
    "What is the most difficult decision you ever took in software?",
    "Tell me about a time you had to be very strategic in order to meet all your top priorities.",
    "Describe a long-term project that you managed. How did you keep everything moving along in a timely manner?",
    "Sometimes it's just not possible to get everything on your to-do list done. Tell me about a time your responsibilities got a little overwhelming. What did you do?",
    "Tell me about a time you set a goal for yourself. How did you go about ensuring that you would meet your objective?",
    "Describe a time when you were the resident technical expert. What did you do to make sure everyone was able to understand you?",
    "Tell me about a time when you had to rely on written communication to get your ideas across to your team.",
    "Tell me about a successful presentation you gave and why you think it was a hit.",
    "Describe a time when you saw some problem and took the initiative to correct it rather than waiting for someone else to do it.",
    "Tell me about a time when you worked under close supervision or extremely loose supervision. How did you handle that?",
    "Give me an example of a time you were able to be creative with your work. What was exciting or difficult about it?",
    "Tell me about a time you were dissatisfied in your work. What could have been done to make it better?",
    "How do you handle a challenge? Give an example.",
    "Describe a decision you made that wasn't popular and how you handled implementing it.",
    "Share an example of how you were able to motivate employees or co-workers.",
    "Tell me about the toughest decision you've had to make in the past six months.",
    "Tell me about a major mistake you made, and what you did to correct it",
    "Tell me about the last time a customer or coworker got upset with you",
    "Tell me about a time you knew you were right, but still had to follow directions or guidelines",
    "Tell me about the last time your workday ended before you were able to get everything done.",
    "Tell me about a time you had to raise an uncomfortable issue with your boss.",
    "Tell me about a goal you failed to achieve.",
    "Tell me about a time you worked on a team with individuals from different cultural backgrounds.",
    "Describe a time when you found it difficult to work with someone from a different background.",
    "Give me an example of a situation where you had to take into account the sensitivities of different parties.",
    "Tell me about a time you observed culturally insensitive behavior on the job.",
    "What experiences have you had with recruiting, hiring, training, and/or supervising a diverse workforce?",
    "Tell me about a time recently when you had to take someone's cultural perspective into account in dealing with them.",
    "When have you worked the hardest?" ,
    "Tell me about a time when you had to juggle multiple important projects.",
    "What was your biggest mistake and what did you learn from it?",
    "Tell me about a decision that you regret.",
    "What's your greatest professional regret?",
    "Describe a situation in which you found a creative way to overcome an obstacle.",
    "Tell me about a time when you came up with a new approach to a problem.",
    "What's the most innovative new idea that you have implemented?",
    "Tell me about two improvements you have made in the last six months.",
    "Describe a time when you anticipated potential problems and developed preventive measures.",
    "Tell me about a time when you had to analyze information and make a recommendation.",
    "Tell me about a time when you demonstrated leadership skills.",
    "When have you delegated effectively?",
    "Describe a time when you led by example.",
    "Who have you coached or mentored to achieve success?",
    "Describe a project that required input from people at different levels in the organization.",
    "Share a rewarding team experience.",
    "Tell me about a time when you worked with a difficult team member.",
    "Give me an example of a team project that failed.",
    "Tell me about a time you stepped up into a leadership role.",
    "Let's say you need something important from a coworker and that person isn't responding. How would you deal with this?",
    "Tell me about a time when you had to manage multiple responsibilities. How did you handle that?",
    "Let's say you're working on a major project and you're in the weeds. How do you find your way out?",
    "We all deal with difficult customers from time to time. Tell me about a challenging client-facing situation and how you handled it.",
    "Sometimes we have an all-hands-on-deck situation that may require everyone to work extra hours. How would you handle that?",
    "Everyone starts somewhere. Talk about a time when you were new on the job and had a lot to learn. How did you manage that?",
    "I'm interested in how you recharge when you're not working. What do you do with your downtime?",
    "Has your manager/supervisor ever asked you to do something that you were uncomfortable with? How did you handle this?",
    "Tell me about a time you witnessed a fellow employee do something that you didn't think was appropriate.",
    "Tell me about a time you made a mistake at work. How did you deal with it?",
    "How have you reacted to a colleague who regularly lets the team down?",
    "Tell me about a time you had to work at a fast pace for an extended period of time. How did you maintain your work pace?",
    "Tell me about the longest time it took you to conclude a deal with a customer.",
    "Describe a situation when you had to overcome a number of obstacles to achieve an objective.",
    "Describe what you do to control mistakes in your work.",
    "Describe a situation in which you had to schedule your activities to meet a work objective.",
    "Describe a new idea or suggestion that you made to your supervisor recently.",
    "Describe a situation when you negotiated with others in your organization to reach agreement.",
    "Tell me about a time you had to quickly adjust your work priorities to meet changing demands.",
    "Tell me about a time you had to make a decision under pressure to meet a deadline",
    "Describe a time when you were faced with a stressful situation and used your coping skills.",
    "Describe a time that you demonstrated the ability to be an effective team member.",
    "Describe a time when you sacrificed short term goals for long term success",
    "Tell me about a time when you had to choose between technologies for a project",
    "Tell me about a time when you disagreed with your hiring manager. What did you do?",
    "Tell me about a time when you had to coach an employee.",
    "Tell me about a time you heard difficult feedback and how you handled it.",
    "Describe a time when you had to convince the leaders of your team despite their disagreement. What did you do convince them?",
    "Tell me about a time when you were not able to meet a time commitment. What prevented you from meeting it? What was the outcome and what did you learn from it?",
    "Describe an example of when you took risk and failed.",
    "Tell me about a time when you overcame an obstacle and delivered results.",
    "Tell me about a time when you disagreed with your boss.",
    "What is the most significant impact of your work inside a team.",
    "Tell me about a time when you helped improve an internal work process. How you did it and what was the result",
    "What is the best invention or idea you had in the past two years?",
    "Tell me about a time you exceeded your expectations.",
    "Describe a project that you are particularly proud of. How did it impact your company? What challenges did you encounter and how did you solve them?",
    "Tell me about a time you had a conflict at work.",
    "Tell me about a time when you took the lead on a difficult project.",
    "Tell me about a time when you received negative feedback from your manager. How did you respond?",
    "How would you handle a project that is expected to be behind schedule.",
    "Describe a time when you received criticism and how you handled it.",
    "Tell me about a time when you had to made a judgement call without having time to refer to a manager/supervisor.",
    "Give me an example where you strongly held an opinion and you were the outlier.",
    "Why Amazon?",
    "Explain a situation where you faced a problem and how did you deal with it.",
    "Tell me about a time you made a decision without consulting your manager.",
    "What's your greatest strength?",
    "Tell me about a time when you were curious; what were your expectations and what you did you learn from them?",
];
